name: Run Unit Tests
run-name: Run Unit Tests
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: pnpm i

      - name: Approve builds
        run: pnpm approve-builds

      - name: Run unit tests
        run: pnpm test
